services:
  - type: web
    name: mechanical-parts-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --preload --threads 4 --timeout 0 --bind 0.0.0.0:$PORT
    autoDeploy: true
build:
  pythonVersion: 3.10.13
